# Generated by Django 3.0 on 2019-12-05 11:50

from django.db import migrations, models
import markdownx.models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=100)),
                ('short_description', martor.models.MartorField()),
                ('body', markdownx.models.MarkdownxField()),
                ('author', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
