# Generated by Django 3.0 on 2019-12-05 12:22

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='body',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='short_description',
            field=models.CharField(max_length=140),
        ),
    ]
