# Generated by Django 3.0 on 2019-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191205_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
    ]
