# Generated by Django 3.0 on 2019-12-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191205_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='is_published',
        ),
    ]
