# Generated by Django 3.0 on 2019-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_articlemodel_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='main_theme',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='1', max_length=9),
        ),
    ]
